{
  "guild": {
    "id": "484437221055922177",
    "name": "Mina Protocol",
    "iconUrl": "https://cdn.discordapp.com/icons/484437221055922177/60f5907d2f7e3804b704a7153cae7768.png?size=512"
  },
  "channel": {
    "id": "1356573276880633986",
    "type": "GuildPublicThread",
    "categoryId": "1047214314349658172",
    "category": "zkapps-questions",
    "name": "Error when proving ContracName.methodName()reading property '2' of undefined",
    "topic": null
  },
  "dateRange": {
    "after": null,
    "before": null
  },
  "exportedAt": "2025-04-23T15:05:34.5890023+04:00",
  "messages": [
    {
      "id": "1356573276880633986",
      "type": "Default",
      "timestamp": "2025-04-01T14:17:53.121+04:00",
      "timestampEdited": null,
      "callEndedTimestamp": null,
      "isPinned": false,
      "content": "After enabling proofs on a localblockchain o1js surprised me with this error.\nIt happens after the contract method - at least after the Provable.log from its last line is printed. \nThe line causing the issue is from account-update.js:\n```\nprover(publicInputFields, MlArray.to(previousProofs))\n```\nI'd appreciate any hints. Thanks!",
      "author": {
        "id": "281785907202228244",
        "name": "anks_",
        "discriminator": "0000",
        "nickname": "anks",
        "color": "#FA7504",
        "isBot": false,
        "roles": [
          {
            "id": "1182371055923376168",
            "name": "Mina Navigator",
            "color": "#FA7504",
            "position": 100
          },
          {
            "id": "1220064445863038996",
            "name": "zkApps",
            "color": "#FFFFFF",
            "position": 19
          }
        ],
        "avatarUrl": "https://cdn.discordapp.com/avatars/281785907202228244/6f18b736e9ac58046f16eafb14817c44.png?size=512"
      },
      "attachments": [],
      "embeds": [],
      "stickers": [],
      "reactions": [],
      "mentions": []
    },
    {
      "id": "1356592378433110037",
      "type": "Default",
      "timestamp": "2025-04-01T15:33:47.286+04:00",
      "timestampEdited": null,
      "callEndedTimestamp": null,
      "isPinned": false,
      "content": "Turns out you need to set `maxProofsVerified` to the exact number of the proof you verify in the program.\n\nhttps://discord.com/channels/484437221055922177/1347637314297401389/1350187882526019655",
      "author": {
        "id": "281785907202228244",
        "name": "anks_",
        "discriminator": "0000",
        "nickname": "anks",
        "color": "#FA7504",
        "isBot": false,
        "roles": [
          {
            "id": "1182371055923376168",
            "name": "Mina Navigator",
            "color": "#FA7504",
            "position": 100
          },
          {
            "id": "1220064445863038996",
            "name": "zkApps",
            "color": "#FFFFFF",
            "position": 19
          }
        ],
        "avatarUrl": "https://cdn.discordapp.com/avatars/281785907202228244/6f18b736e9ac58046f16eafb14817c44.png?size=512"
      },
      "attachments": [],
      "embeds": [],
      "stickers": [],
      "reactions": [],
      "mentions": []
    }
  ],
  "messageCount": 2
}